#项目配置文件
[package]
name = "os"
version = "0.1.0"
authors = ["chilltycho <chilltycho@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
